### ISSUE TITLE
long_int_negate

### ISSUE THREAD

**Issue by I8087** [I8087/mlib#3]
The MikeOS function `long_int_negate` takes and returns a 32-bit value held in DX:AX Unfortunately, SmallerC doesn't support long types, so a special structure should be used and implemented like the one below.

``` C
typedef struct b_int {
    int low;
    int high;
} b_int;
```

**Comment by ghost** [comment]
Thanks!
I have this bug in my library as well.
Also, be careful with your implementation of 'long_int_to_string' when you add the String API.

I have currently implemented it as: 
`char *os_long_int_to_string(int lower_part, int upper_part, int base, char *buffer);`
However, your idea of using a structure sounds much more sane.

**Comment by I8087** [comment]
Yeah, structures sure do come in handy! I see you've pushed a commit that implemented `longint`. Does the assembly code that handles the structure work? Anyhow, I'll check out and test your library later tonight or tomorrow.

**Comment by ghost** [comment]
My implementation has been tested on my 2048 game written with my C library and confirmed to work. In fact, the setup of the structure means the data is stored in the same as a 32-bit variable would be stored in memory.

I did have to make the variables unsigned type as it caused confusing when my program tried to add the lower halves. 

I am passing all structures by reference at the moment, as I want to avoid wasting stack space as much as possible. My stack space is limited currently.

**Comment by I8087** [comment]
Curious, do you have functions likes `bigint_add()` and `bigint_sub()`? If not, a spin off library might be in order!

**Comment by ghost** [comment]
Nope. My 2048 program just has it's own `bigint_add()` routine to calculate scores and uses the libmikeos to provide to the structure type. This could provide very useful going forward. Perhaps some kind of very simple large integer library?

**Comment by I8087** [comment]
Yeah, and it could easily be portable for other C compiler's too.
